### ISSUE TITLE
Написать тесты на PerkResolver.ApplyProgress на проверку LevelCap

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon#10]
Если достигнут LevelCap перка (максимальный уровень развития), то его прогресс больше не увеличивается.

**Comment by dcorriveau** [comment]
Isn't this issue fixed by: ApplyProgress_PerkIsLevelCap_PerkDosntLeveledUp()?

**Comment by kreghek** [comment]
@dcorriveau Yes, you are right :-)

**Comment by kreghek** [comment]
> Isn't this issue fixed by: ApplyProgress_PerkIsLevelCap_PerkDosntLeveledUp()?

@dcorriveau Yes, you are right :-)
