### ISSUE TITLE
Исправит замечание анализатора: MapBase: Remove the member initializer, all constructors set an initial value for the member.

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon#20]

**Comment by dcorriveau** [comment]
Hey @kreghek!

I was hoping to understand this request. Are you just looking for member initalizers to be removed from MapBase? Or are you looking for an implementation of HexBase as well?

Just wanted a bit more detail on this issue/task :)

**Comment by kreghek** [comment]
Hi, @dcorriveau 

(sorry for my english)

It was Code Smell from Sonar. Now _nodeBlockers initialied twice: in constructor and has field initialier. We have to remove field initializer.

![image](https://user-images.githubusercontent.com/2405499/46593742-8b25a380-caf8-11e8-9cb0-e677a4c840ce.png)
